[build]
  command = "npm run build"
  publish = "public"  # Direktori publik situs web Anda

[[redirects]]
  from = "/*"  # Mengarahkan semua permintaan ke root situs web
  to = "/:splat"
  status = 200
